spring:
  application:
    name: configuracion-centralizada

  cloud:
    config:
      server:
        git:
          uri: https://github.com/eliasmoranurcia10/configuracion-centralizada.git

server:
  port: 8888
